import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'


import { useEffect, useLayoutEffect, FC } from 'react'
import { SpinePlayer } from '@esotericsoftware/spine-player'

const inter = Inter({ subsets: ['latin'] })




export default function Home() {

  useEffect(() => {
    const spinePlayer = new SpinePlayer("animation-custom", {
      preserveDrawingBuffer: true,
      jsonUrl: "assets/spineSprites/HellyGirl/Hellbenders.json",
      atlasUrl: "assets/spineSprites/HellyGirl/HellyGirl_Skins2.atlas",
      premultipliedAlpha: true,
      backgroundColor: "#cccccc",
      viewport: {
        debugRender: true,
      },
      showControls: true,
      skins: ['Characters/Helly8', 'Weapons/Chainsaw'],

    })

  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={ `${styles.main} ${inter.className}` }>

        <div style={ { width: '100%', height: '50%' } } id='animation-custom'></div>

      </main>
    </>
  )
}
